version: '3.1'
services:
  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: middleProject
volumes:
  db: